### ISSUE TITLE
Instructor Feedback - Project Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [mhill10/SalonSolutions#4]
Time to start rolling on your indie project!  Let me know when the following are ready and I'll review for checkpoint 2:

- [x] DB design
- [x] Hibernate (include screenshots showing unit tests passing for at least one entity Dao)
- [x] Update time log (and continue updating regularly - at least weekly)
- [x] readme.md needs updating (I don't think the NOAA service is relevant ;))  Only include the tech you are actually targeting here.
- [x] Update project plan to be relevant for your project.

**Comment by mhill10** [comment]
Hi @pawaitemadisoncollege... thank you for the feedback.  Per your suggestions, I have implemented verbiage and project planning that better pertains to my Indie Project (rather than yours).  I also adjusted my DB design to only account for one user class, rather than multiple user classes (as you and I discussed face-to-face last week).  I am continuing to struggle to get my UserDaoTest class to function properly.  Have a help message out to Slack currently.  Will see if I can get things better dialed-in before class today.  Any points you are able to award for the aforementioned efforts are greatly appreciated.  If not, I understand.  Thank you.

**Comment by pawaitemadisoncollege** [comment]
Nice job finishing up the checkpoint.

A few things:

- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertEquals(expectedUser, actualUser);` so that you don't have to compare each instance var/column manually like this: https://github.com/mhill10/SalonSolutions/blob/bdd35d505e862045101ec02c43c3055ab37f42d5/src/test/java/edu/matc/persistence/UserDaoTest.java#L50-L58
- [ ] Time to implement the generic Dao!
- [ ] Project plan has some trail references? "Build the trail search jsp Build the trail add/update/delete jsp"
- [ ] Project plan formatting could be improved - for example, the week 8 section should be bullet pointed for easier reading.
